version: "3.8"

services:
  xray:
    build: ./docker
    container_name: xray
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./clients:/app/clients
      - ./xray:/app/xray
      - ./.env:/app/.env
    command: []
